### ISSUE TITLE
grunt watch: run browserify on template change

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/snug#10]

**Comment by Charlotteis** [comment]
Hey @gr2m, looks like we are now doing this, as far as I can tell on this line: https://github.com/hoodiehq/snug/blob/master/Gruntfile.js#L32

I just want to make sure I'm correct before I close this issue, thanks!

**Comment by boennemann** [comment]
@svnlto changed that here: https://github.com/hoodiehq/snug/commit/51075d2f28d8185ba36fe88adf964ecef488fa23 two months later, so I think it's done.
